# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ba5afc08fc7980301cda22a46bb31759440e45bb1b54d0e20881fedde2fc2445912c6a995416e64bdaef43d784194d30df333fd1dbf12881ed2fcfb248ddfba

test:
  secret_key_base: 72ca300d521f192f02ccde5d987e5848bbcccebc70b7a783e2e3b7efafc27c997ebd8699472ab3370bc5c8871c35fa376fe33fbaebfd2af474ecec6956ff9adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
